import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FilterDialog } from "@/components/provider/filter-dialog";
import { SettingsDialog } from "@/components/provider/settings-dialog";
import { ChatInitializer } from "@/components/provider/chat-initializer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-screen flex flex-row dark:bg-zinc-800">
          {children}
        </div>
        <ChatInitializer />
        <FilterDialog />
        <SettingsDialog />
      </body>
    </html>
  );
}
